version: '3'
services:
  eureka-service:
    image: eureka-discovery-service
    ports:
     - "8761:8761"

  quote-service-1:
    image: quote-service
    ports:
     - "7000:8080"
    links:
     - eureka-service

  quote-service-2:
    image: quote-service
    ports:
     - "7001:8080"
    links:
     - eureka-service

  monitoring-service:
    image: monitoring-service
    ports:
     - "8081:8081"
    links:
     - eureka-service

  api-gateway-service:
    image: api-gateway-service
    ports:
     - "9000:9000"
    links:
     - eureka-service

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: logstash
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
     - ./logstash:/etc/logstash/conf.d
    ports:
     - "5000:5000"
    links:
     - elasticsearch

  kibana:
    image: kibana
    container_name: kibana
    environment:
     - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
     - "5601:5601"
    links:
     - elasticsearch

volumes:
  esdata1:
    driver: local
