server:
  port: 9000
spring:
  application:
    name: api-gateway-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
zuul:
  routes:
    comment:
      path: /quote/**
      serviceId: quote-service